In [4]:
import numpy as np

In [8]:
#buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[19, 2, 4],
              [25, 15, 7]])
x

array([[19,  2,  4],
       [25, 15,  7]])

In [9]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [10]:
 # tampilkan seluruh elemen dari kolom pertama dari matrix
x[:,0]

array([19, 25])

In [11]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1,:]

array([25, 15,  7])

In [15]:
import torch

In [16]:
# buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[19,2,4],
               [25,15,7]])
x_pt


tensor([[19,  2,  4],
        [25, 15,  7]])

In [17]:
# tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [19]:
# # tampilkan seluruh elemen dari kolom pertama dari matrix
x_pt[:,0]

tensor([19, 25])

In [20]:
# tampilkan seluruh elemen dari baris kedua dari matrix
x_pt[1,:]

tensor([25, 15,  7])

In [24]:
import tensorflow as tf

In [26]:
# buat matrix x berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[19,2,4],
                    [25,25,7]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[19,  2,  4],
       [25, 25,  7]], dtype=int32)>

In [25]:
# tampilkan ukuran dari matrix x
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [27]:
 # tampilkan seluruh elemen dari kolom pertama dari matrix x
 x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([19, 25], dtype=int32)>

In [28]:
# tampilkan seluruh elemen dari baris kedua dari matrix x
x_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 25,  7], dtype=int32)>