In [1]:
import numpy as np

In [60]:
# buat vector x dengan ukuran 3x1
x = np.array([19,1,9])
x

array([19,  1,  9])

In [61]:
# hitung panjang vector x
len(x)

3

In [62]:
# tampilkan ukuran vector x
x.shape

(3,)

In [63]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [17]:
# akses elemen pertama dari vector x
x[0]

np.int64(19)

In [64]:
# tampilkan tipe data elemen pertama dari vector x
type (x[0])

numpy.int64

In [65]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([19,  1,  9])

In [66]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [82]:
# buat vector y dengan ukuran 3x1
y = np.array([19,1,9])
y

array([19,  1,  9])

In [68]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t


array([19,  1,  9])

In [69]:
# tampilkan ukuran dari vector y_t
y_t.shape

(3,)

In [70]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [71]:
# pytorch
y_pt = torch.tensor([19,1,9])
y_pt

tensor([19,  1,  9])

In [81]:
# Tensorflow
y_tf = tf.Variable([19,1,9])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([19,  1,  9], dtype=int32)>

In [83]:
# lakukan transpose pada vector y_pt dan simpan pada variabel y_pt_t
y_pt_t = y_pt.T
y_pt_t

/tmp/ipykernel_9083/328932866.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  y_pt_t = y_pt.T


tensor([19,  1,  9])

In [85]:
# lakukan transpose pada vector y_tf dan simpan pada variabel y_tf_t
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([19,  1,  9], dtype=int32)>

In [86]:
# tampilkan ukuran dari vector y_pt_t
y_pt_t.shape

torch.Size([3])

In [87]:
# tampilkan ukuran dari vector y_tf_t
y_tf_t.shape

TensorShape([3])